### ISSUE TITLE
Don't json.dumps() unnecessarily

### ISSUE THREAD

**Issue by coryvirok** [rollbar/rollbar-agent#15]
In `_build_payload()` we `json.dumps()` only to `json.loads()` later in `_process_line()`. We shouldn't have to use `json.dumps()` if we call `requests.post()` with the dict instead of a string.

**Comment by rokob** [comment]
`_build_payload()` calls `json.dumps()` but that is independent of `_process_line()` and the `json.loads()` that happens there. We can only not call `json.dumps()` and pass a dict directly to `requests.post()` if we use the `json` option instead of `data` which was added in v2.4.2 of the requests library. We are pointing at >=0.13.1 so we would either have to upgrade or keep calling `json.dumps()` ourselves.

I have a feeling this issue is referring to dead code at this point because the current state of the code does not call load after dump. We do call dump after load only in the scenario where the access token was missing from the payload line. So we currently do not call dump unnecessarily. We probably used to but things have been refactored so closing this.
