### ISSUE TITLE
rollbar-agent wouldn't stop via sudo command

### ISSUE THREAD

**Issue by jessewgibbs** [rollbar/rollbar-agent#31]
Details in https://app.clubhouse.io/rollbar/story/22253/rollbar-agent-wouldn-t-stop-via-sudo-command-for-one-user

**Comment by rokob** [comment]
The report here is that `sudo service rollbar-agent stop` did not stop the rollbar-agent process but directly killing the process worked. The init.d script looks correct in that stop will try to send a SIGTERM if the pid file exists, otherwise it will use ps to find the pid and send a SIGKILL. So if doing a `kill -9 pid` worked directly, then using `service stop` should have also worked unless somehow the pidfile got corrupted. We would need to know exactly what sequence of commands worked and didn't work, the output of ps that got the pid for the manual kill, and the existence and contents of the relevant pidfile. Otherwise the fact that this happened once is not much to go on. I'm going to close this and will investigate if some other piece of information comes up.
