### ISSUE TITLE
Question about branch config parameter

### ISSUE THREAD

**Issue by olafnorge** [rollbar/rollbar-agent#43]
Hi,

I am running a PHP application with the rollbar-php SDK installed. I am interested in getting rid of the delay of synchronous error sending within a request.

Your project looks promising but I am wondering what I should do with the agent config when I run a deployment of my application. Wondering because I need to configure the `params.branch` parameter to map errors to a git tag but for the changes taking effect I would need to restart the agent.

I am deploying with an unprivileged user but for the agent restart I would need to be root. 

Is there any other way of setting the branch without a restart of the agent?

**Comment by rivkahstandig3636** [comment]
@rokob Could you take a look at this?

**Comment by jessewgibbs** [comment]
Closing this question since it's 2 months old.  If this is still important, please reopen it.

**Comment by olafnorge** [comment]
@jessewgibbs sure it is still important as I didn't get any valuable answer to my question yet.

**Comment by olafnorge** [comment]
@jessewgibbs please reopen the ticket. I can't do it for any reason.

**Comment by brianr** [comment]
@olafnorge You shouldn't need to do anything with `params.branch`, since you're just use rollbar-agent as a relay for payloads that have already been written by rollbar-php. You can configure the branch, and all other params in the payload, at the *php* level, and then rollbar-agent will pass them along as-is.

params.branch etc. are only needed when you are using rollbar-agent to parse log files.

Does that make sense and answer your question?

**Comment by olafnorge** [comment]
Hi @brianr, it does thx for clarification.
